import os
import sqlite3
from dotenv import load_dotenv
from typing import TypedDict, List, Annotated
from operator import add
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage, AIMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver
from pydantic import BaseModel, Field
from typing import TypedDict, List, Annotated, Literal
from langchain_core.runnables.config import RunnableConfig
import sqlparse
import functools
import time

# 1. Load environment variables from the .env file (API keys)
load_dotenv()


def _require_openai_credentials() -> None:
    """Fail fast with a clear message when OpenAI credentials are missing."""
    if os.getenv("OPENAI_API_KEY") or os.getenv("OPENAI_ADMIN_KEY"):
        return

    raise RuntimeError(
        "Missing OpenAI credentials. Set OPENAI_API_KEY in the project .env file "
        "or export OPENAI_API_KEY before starting the app."
    )


_require_openai_credentials()

# 2. Define the Agent's Memory
class AgentState(TypedDict, total=False):
    """
    Defines the shared state for the Text-to-SQL agent graph.
    """
    query: str                  # The user's natural language question
    standalone_query: str       # The context-enriched question
    query_complexity: Literal["simple", "complex", "out_of_scope"] # Router classification
    classification_reason: str  # Explanation of the classification
    sql_plan: str               # Step-by-step join plan for complex queries
    sql_query: str              # The SQL query generated by the LLM
    db_results: str             # The raw data returned from the SQLite database
    raw_data: list              # Structured data for the Streamlit UI dataframe
    error: str                  # Any SQL execution error
    retry_count: int            # Track the number of SQL correction attempts
    summary: str                # The final, business-friendly answer
    chart_type: str             # Stores the LLM's choice of visualization
    messages: Annotated[List[BaseMessage], add] 

class QueryClassification(BaseModel):
    """Schema for the semantic router output."""
    complexity: Literal["simple", "complex", "out_of_scope"] = Field(
        description="Categorize the query. 'out_of_scope' if it cannot be answered by the schema. 'simple' if it requires 1-2 tables and basic filtering. 'complex' if it requires 3+ tables, advanced math, or complex aggregations."
    )
    reason: str = Field(description="Explain why this category was chosen.")

class SummaryOutput(BaseModel):
    """Schema for the final summary and chart type selection."""
    summary: str = Field(description="The natural language summary of the data.")
    chart_type: Literal["bar", "line", "pie", "none"] = Field(
        description="The best chart type to visualize this data. Use 'bar' for comparisons, 'line' for time series/trends, 'pie' for proportions, and 'none' if it's a single number or unchartable."
    )

@functools.lru_cache(maxsize=1)
def get_schema() -> str:
    """
    Loads the database schema from disk once and caches it in RAM.
    Eliminates redundant disk I/O operations across nodes.
    """
    print("⚙️ Loading schema into memory cache...")
    try:
        with open("data/schema.txt", "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "Schema file not found."

# 2.5 Define Node: Contextualizer / Reformulator
def reformulate_query(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node 0: Analyzes the user's latest question and the conversation history.
    If the question refers to past context (e.g., "What about the second one?"),
    it rewrites it into a standalone question containing all necessary context.
    """
    print("--- NODE: REFORMULATING QUERY (CONTEXT MANAGEMENT) ---")
    query = state.get("query")
    messages = state.get("messages", [])

    model_name = config.get("configurable", {}).get("model_name", "gpt-4o-mini")
    
    # If there is no history (just the current prompt), no need to reformulate
    if len(messages) <= 1:
        print("No history detected. Keeping original query.")
        return {"standalone_query": query}
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    
    # We extract the chat history (excluding the very last message which is the current query)
    history_text = "\n".join([f"{msg.type}: {msg.content}" for msg in messages[:-1]])
    
    system_prompt = f"""You are an expert context manager.
    Your task is to rewrite the user's latest question into a fully standalone question, 
    incorporating any necessary context (like specific categories, filters, or entities) mentioned in the conversation history.
    
    CONVERSATION HISTORY:
    {history_text}
    
    LATEST QUESTION: {query}
    
    CRITICAL RULES:
    1. If the latest question is already standalone and changes the subject, just return the latest question as is.
    2. If it refers to previous answers (e.g., "Which of these", "Sort them", "What about..."), replace the pronouns with the actual specific entities from the history.
    3. Return ONLY the rewritten question string, nothing else.
    """
    
    response = llm.invoke([SystemMessage(content=system_prompt)])
    rewritten_query = response.content.strip()
    
    print(f"Original: {query}")
    print(f"Rewritten: {rewritten_query}\n")
    
    return {"standalone_query": rewritten_query}

# 2.7 Define Node: Semantic Router (Classifier)
def classify_query(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node: Categorizes the query to determine the optimal execution path.
    """
    print("--- NODE: CLASSIFYING QUERY ---")
    query = state.get("standalone_query")

    model_name = config.get("configurable", {}).get("model_name", "gpt-4o-mini")
    
    # Fetch the schema from memory cache
    schema = get_schema()
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(QueryClassification)
    
    system_prompt = f"""You are a Lead Data Architect routing SQL requests.
    Analyze the user's question against the database schema.
    
    SCHEMA:
    {schema}
    """
    
    result = structured_llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Question: {query}")
    ])
    
    print(f"Classification: {result.complexity.upper()} - {result.reason}\n")
    
    # If out of scope, we pre-fill the summary to answer immediately
    summary = result.reason if result.complexity == "out_of_scope" else ""
    messages_to_add = [AIMessage(content=summary)] if summary else []
    
    return {
        "query_complexity": result.complexity,
        "classification_reason": result.reason,
        "summary": summary,
        "messages": messages_to_add
    }

# 2.8 Define Node: SQL Planner (For Complex Queries Only)
def plan_sql_query(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node: Acts as a 'Chain-of-Thought' step. Writes a strategic plan of which 
    tables to join and what filters to apply before writing the actual SQL.
    """
    print("--- NODE: PLANNING COMPLEX SQL ---")
    query = state.get("standalone_query")

    model_name = config.get("configurable", {}).get("model_name", "gpt-4o-mini")
    
    # Fetch the schema from memory cache
    schema = get_schema()
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    
    system_prompt = f"""You are a Senior SQL Architect. 
    Before writing a complex query, you must plan the execution step-by-step.
    Identify the necessary tables, the exact foreign keys for JOINs, and the required math/aggregations.
    Do NOT write the SQL code. Only write the execution plan.
    
    SCHEMA:
    {schema}
    """
    
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Plan the SQL execution for this question: {query}")
    ])
    
    plan = response.content.strip()
    print(f"Plan generated.\n")
    
    return {"sql_plan": plan}

# 3. Define Node 1: SQL Generator
def generate_sql(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node 1: Takes the user query and the database schema, 
    and uses an LLM to generate a valid SQLite query.
    If an error occurred in a previous step, it uses it to self-correct.
    """
    print("--- NODE: GENERATING SQL ---")

    # Extract runtime configurations
    configurable = config.get("configurable", {})
    model_name = configurable.get("model_name", "gpt-4o-mini")
    use_few_shot = configurable.get("use_few_shot", True)

    question = state.get("standalone_query")
    error = state.get("error", "")
    
    # Fetch the schema from memory cache
    schema = get_schema()
        
    # Initialize the LLM with the specified model and temperature.
    # Temperature is set to 0 because we want deterministic, precise SQL code, not creativity
    llm = ChatOpenAI(model=model_name, temperature=0)
    
    # Define Few-Shot Examples to improve LLM accuracy (In-Context Learning)
    few_shot_examples = """
    --- FEW-SHOT EXAMPLES ---
    Example 1 (Basic Aggregation & Filtering):
    User: "Combien y a-t-il de clients dans la ville de sao paulo ?"
    SQL: SELECT COUNT(customer_id) FROM customers WHERE customer_city = 'sao paulo';

    Example 2 (Complex Joins & Language Translation):
    User: "Quel est le top 3 des catégories avec le plus grand nombre d'articles vendus ?"
    SQL: SELECT ct.product_category_name_english, COUNT(oi.order_item_id) AS total_items FROM order_items oi JOIN products p ON oi.product_id = p.product_id JOIN category_translation ct ON p.product_category_name = ct.product_category_name GROUP BY ct.product_category_name_english ORDER BY total_items DESC LIMIT 3;

    Example 3 (Date Handling in SQLite):
    User: "Combien de commandes ont été livrées en 2018 ?"
    SQL: SELECT COUNT(order_id) FROM orders WHERE order_status = 'delivered' AND strftime('%Y', order_delivered_customer_date) = '2018';
    -------------------------
    """

    # Craft the main system prompt
    system_prompt = f"""You are an expert SQLite data analyst.
    Your task is to translate the user's question into a valid SQLite query.
    
    Here is the schema of the database:
    {schema}
    
    Rules:
    1. Return ONLY the raw SQL query.
    2. Do not wrap the SQL in markdown formatting (e.g., no ```sql).
    3. Do not add any explanations or text.
    4. Use JOINs correctly based on the provided schema.
    5. CRITICAL LANGUAGE & FORMAT RULE: The database only stores category names in Portuguese (product_category_name) and English (product_category_name_english). Furthermore, the English names are ALWAYS formatted in lowercase with underscores instead of spaces (e.g., 'health_beauty', 'watches_gifts'). If the chat history mentions categories in French, translate them to English AND format them with lowercase and underscores for the WHERE clause.
    """

    # Inject Few-Shot examples ONLY if enabled by the user/dashboard
    if use_few_shot:
        system_prompt += f"\n{few_shot_examples}\n"
    
    # Self-correction logic: if the state contains an error from a previous run
    if error:
        system_prompt += f"\n\nWARNING: Your previous query failed with this error: {error}. Please correct your SQL."

    # If there's a pre-written execution plan (for complex queries), we inject it into the prompt to guide the SQL generation
    plan = state.get("sql_plan", "")
    if plan:
        system_prompt += f"\n\nCRITICAL: Follow this architectural plan to write your SQL:\n{plan}"

    # Combine the system prompt with the entire conversation history (which now includes the latest question)
    messages = [SystemMessage(content=system_prompt), HumanMessage(content=question)]
    
    # Call the LLM
    response = llm.invoke(messages)
    generated_sql = response.content.strip()
    
    print(f"Generated SQL:\n{generated_sql}\n")
    
    # Return the updated state
    return {"sql_query": generated_sql}

# 4. Define Node 2: Database Executor
def execute_sql(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node 2: Executes the generated SQL query against the SQLite database.
    If it succeeds, it returns the data. If it fails, it returns the exact SQL error.
    """
    print("--- NODE: EXECUTING SQL ---")
    sql_query = state.get("sql_query", "")

# --- STRICT SECURITY GUARDRAIL (AST PARSER) ---
    # Parse the raw SQL string into distinct structural statements
    parsed_statements = sqlparse.parse(sql_query)
    
    for statement in parsed_statements:
        # Ignore empty statements (like trailing semicolons or pure comments)
        if not statement.is_whitespace:
            # get_type() returns the core command type (e.g., 'SELECT', 'DROP') or None
            raw_type = statement.get_type()
            
            # Guard: If raw_type is None (e.g., pure comments), we ignore it safely
            if raw_type:
                stmt_type = raw_type.upper()
                
                # Strict Read-Only policy: Only SELECT statements are allowed
                if stmt_type != 'SELECT':
                    security_error = f"Security Violation: '{stmt_type}' operation detected. Only SELECT queries are strictly allowed."
                    print(f"🚨 ALERT: {security_error}")
                    
                    # Return the security error to force the agent to self-correct or abort
                    current_retries = state.get("retry_count", 0)
                    return {"error": security_error, "retry_count": current_retries + 1}
        
    # Initialize conn to None so it exists in the local scope for the finally block
    conn = None
    
    try:
        # Connect to the local SQLite database
        conn = sqlite3.connect("data/olist.db")
        cursor = conn.cursor()
        
        # --- TIMEOUT MECHANISM (Anti-Cross Join) ---
        start_time = time.time()
        TIMEOUT_SECONDS = 5.0 # Max allowed time in seconds
        
        def progress_handler():
            # If elapsed time exceeds limit, return 1 to force abort
            if time.time() - start_time > TIMEOUT_SECONDS:
                return 1 
            return 0
            
        # SQLite will call this function every 10,000 internal instructions
        conn.set_progress_handler(progress_handler, 10000)
        # ------------------------------------------------
        
        # Execute the SQL query
        cursor.execute(sql_query)
        
        # Disable the progress handler once the query is done
        conn.set_progress_handler(None, 0)
        
        # Fetch results (limiting to 100 to avoid blowing up the LLM context later)
        results = cursor.fetchmany(100)
        
        # Extract column names for better readability
        column_names = [description[0] for description in cursor.description]
        
        # Create a structured list of dictionaries for Streamlit
        raw_data_list = [dict(zip(column_names, row)) for row in results]
        
        # Format the output SPECIFICALLY for the LLM (Context limitation)
        if not results:
            formatted_results = "No results found."
        else:
            formatted_results = f"Columns: {', '.join(column_names)}\nData:\n"
            
            # 1. Row Limit: We only send a maximum of 10 rows to the LLM
            llm_row_limit = 10
            for row in results[:llm_row_limit]:
                formatted_results += str(row) + "\n"
                
            # If the DB returned more than 10 rows, we append a strict instruction for the LLM
            if len(results) > llm_row_limit:
                hidden_rows = len(results) - llm_row_limit
                formatted_results += f"\n... (WARNING: {hidden_rows} additional rows were retrieved but hidden from you to save tokens. You MUST mention to the user that this is a partial view and they should look at the table/CSV for the full data.)\n"
            
            # 2. Hard Character Limit: Ultimate fallback in case a single row contains massive text (e.g., long reviews)
            max_chars = 3000
            if len(formatted_results) > max_chars:
                formatted_results = formatted_results[:max_chars] + "\n... [FATAL: DATA TRUNCATED DUE TO EXTREME LENGTH]"
                
        print("✓ Execution successful. Data fetched.\n")
        
        # We return both the raw data list for the UI and a formatted string for the LLM summary node.
        # We also clear any previous errors and keep track of retries for evaluation purposes.
        current_retries = state.get("retry_count", 0)
        
        # Return the results, clear errors, BUT keep the historical retry count for evaluation
        return {
            "db_results": formatted_results, 
            "raw_data": raw_data_list, 
            "error": "", 
            "retry_count": current_retries 
        }
        
    except sqlite3.OperationalError as e:
        # This captures SQL syntax errors, missing tables/columns, and also our custom timeout error from the progress handler
        if "interrupted" in str(e):
            error_msg = f"SQLite Error: Execution timed out after {TIMEOUT_SECONDS} seconds. Your query is too slow. Check for missing ON clauses in your JOINs (Cartesian products)."
        else:
            error_msg = f"SQLite Error: {str(e)}"
            
        print(f"✗ Execution failed! {error_msg}\n")
        current_retries = state.get("retry_count", 0)
        return {"error": error_msg, "retry_count": current_retries + 1}
        
    except Exception as e:
        # Catch any other unforeseen errors to prevent the agent from crashing and to provide feedback for self-correction
        error_msg = f"System Error: {str(e)}"
        print(f"✗ Execution failed! {error_msg}\n")
        current_retries = state.get("retry_count", 0)
        return {"error": error_msg, "retry_count": current_retries + 1}
        
    finally:
        # --- Guaranteed Connection Cleanup ---
        # This block ALWAYS executes, whether the try succeeds or raises an exception
        if conn:
            conn.close()

# 5. Define Node 3: Synthesizer / Summarizer
def summarize_results(state: AgentState, config: RunnableConfig) -> dict:
    """
    Node 3: Takes the raw database results and translates them into a 
    clear, business-friendly summary using the LLM.
    Also determines the best chart type to visualize the data.
    """
    print("--- NODE: SUMMARIZING RESULTS ---")
    
    # We use the standalone query if it exists, otherwise fallback to the original query
    question = state.get("standalone_query", state.get("query"))
    raw_data = state.get("db_results")
    error = state.get("error")

    model_name = config.get("configurable", {}).get("model_name", "gpt-4o-mini")
    
    # If there's an error and we ended up here, it means we reached the max retry limit (3/3)
    if error:
        failure_msg = f"Sorry, I couldn't extract this data after several self-correction attempts. Final technical error: {error}"
        print("✗ Max retries failed. Returning error summary.\n")
        return {
            "summary": failure_msg, 
            "chart_type": "none", # Fallback for error states
            "messages": [AIMessage(content=failure_msg)]
        }
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    
    # Force the LLM to output the structured format
    structured_llm = llm.with_structured_output(SummaryOutput)
    
    system_prompt = """You are a helpful business data analyst. 
    You are provided with a user's original question and the raw data results from a SQL database.
    Your job is to write a clear, concise, and professional answer.
    
    CRITICAL RULES:
    1. Explicitly list the key data points in your natural language response. 
    2. Do not mention SQL, databases, or raw formatting.
    3. Determine the best type of chart to visualize this data based on the question and the data shape.
    4. LANGUAGE: You MUST answer in the EXACT SAME LANGUAGE as the user's original question. If the user asks in French, your final summary must be entirely in French.
    """
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Question: {question}\n\nRaw Data:\n{raw_data}")
    ]
    
    # Invoke the structured LLM
    response = structured_llm.invoke(messages)
    
    print(f"✓ Summary generated. Chosen chart: {response.chart_type.upper()}\n")
    return {
        "summary": response.summary, 
        "chart_type": response.chart_type,
        "messages": [AIMessage(content=response.summary)] 
    }

# 6. Define the Routing Logic (Conditional Edge)
def check_for_errors(state: AgentState, config: RunnableConfig) -> str:
    """
    Decides where the agent should go next after executing the SQL.
    If there is an error, route back to the SQL Generator to fix it (max 3 times).
    If the max retry limit is reached, route to the Summarizer to report the failure.
    If successful, route directly to the Summarizer.
    """
    error = state.get("error")
    retries = state.get("retry_count", 0)

    # Extract runtime config for self-correction
    configurable = config.get("configurable", {})
    use_self_correction = configurable.get("use_self_correction", True)
    
    if error:
        # If self-correction is disabled, we skip straight to the summary with the error message
        if not use_self_correction:
            print("--- ROUTING: SELF-CORRECTION DISABLED. FORCING END. ---")
            return "summarize_results"

        # Check if we have hit the maximum number of allowed retries
        if retries >= 3:
            print(f"--- ROUTING: MAX RETRIES REACHED ({retries}/3). STOPPING LOOP. ---")
            return "summarize_results"
        else:
            # We still have retries left, loop back to the SQL Generator
            print(f"--- ROUTING: ERROR DETECTED, RETRYING SQL GENERATION (Attempt {retries}/3) ---")
            return "generate_sql"
    else:
        # No error means the SQL executed perfectly
        print("--- ROUTING: SUCCESS, PROCEEDING TO SUMMARY ---")
        return "summarize_results"

# 7. Build and Compile the Graph
def create_graph():
    memory = MemorySaver()
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("reformulate_query", reformulate_query)
    workflow.add_node("classify_query", classify_query)
    workflow.add_node("plan_sql_query", plan_sql_query)
    workflow.add_node("generate_sql", generate_sql)
    workflow.add_node("execute_sql", execute_sql)
    workflow.add_node("summarize_results", summarize_results)
    
    workflow.add_edge(START, "reformulate_query")
    workflow.add_edge("reformulate_query", "classify_query")
    
    # Advanced Semantic Router
    # se 'RunnableConfig' as type hint so LangGraph knows to inject it automatically
    def route_after_classification(state: AgentState, config: RunnableConfig) -> str:
        cat = state.get("query_complexity")

        # Read the ablation study flag safely
        safe_config = config or {}
        use_cot_planner = safe_config.get("configurable", {}).get("use_cot_planner", True)

        if cat == "out_of_scope":
            print("--- ROUTING: OUT OF SCOPE. ENDING. ---")
            return END
        elif cat == "complex":
            if use_cot_planner:
                print("--- ROUTING: COMPLEX QUERY. CoT PLANNER ENABLED. GOING TO PLANNER. ---")
                return "plan_sql_query"
            else:
                print("--- ROUTING: COMPLEX QUERY. CoT PLANNER DISABLED. GOING DIRECTLY TO SQL. ---")
                return "generate_sql"
        else: # simple
            print("--- ROUTING: SIMPLE QUERY. GOING DIRECTLY TO SQL. ---")
            return "generate_sql"
            
    workflow.add_conditional_edges(
        "classify_query",
        route_after_classification,
        {
            END: END,
            "plan_sql_query": "plan_sql_query",
            "generate_sql": "generate_sql"
        }
    )
    
    workflow.add_edge("plan_sql_query", "generate_sql") # Planner always goes to SQL
    workflow.add_edge("generate_sql", "execute_sql")
    
    workflow.add_conditional_edges("execute_sql", check_for_errors, {"generate_sql": "generate_sql", "summarize_results": "summarize_results"})
    workflow.add_edge("summarize_results", END)
    
    return workflow.compile(checkpointer=memory)

# 8. Quick Test Block
if __name__ == "__main__":
    # Initialize the compiled LangGraph agent
    agent_graph = create_graph()
    
    # We ask a trick question: the schema DOES NOT have a customer "name" column.
    # This should force the LLM to make a mistake, triggering the self-correction loop!
    test_state = {"query": "Can you give me the names of 3 customers from sao paulo?"}
    
    print("🚀 Starting the agentic workflow...\n")
    
    # Invoke the graph
    final_state = agent_graph.invoke(test_state)
    
    print("\n=== FINAL BUSINESS ANSWER ===")
    print(final_state.get("summary"))